name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest 
    permissions:
      actions: read
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - name: Set up JDK 17
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}/.m2 # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish package
        run: mvn --batch-mode deploy ## mvn deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
