name: "Publish package to GitHub Packages"

on:
  release:
    types: [created]
    branches: [ main ]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest 
    permissions: 
      actions: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
